
CREATE TABLE `truck` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `XTBH` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '违法监测系统编号',
  `WorksNo` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '厂商编码',
  `DeviceNo` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '设备编码由交管局统一分配',
  `Type` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '数据包类型填写编码Z(监测数据包)',
  `CarNo` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '车牌号形如京A12345样式',
  `Confidence` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '牌照识别的可信度 0 到1 的小数值 保留两位小数',
  `CarType` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '车型代表大车小车形如1样式',
  `PlateColor` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '号牌颜色，具体代码由交管局统一制定下发',
  `CarLogo` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '车辆标志，代表厂商车辆标志 ，形如0001样式',
  `Direction` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '行驶方向编码',
  `CarRoad` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '车道标识符',
  `CarSpeed` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '车速，形如120.00样式 单位公里/小时',
  `UploadType` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '定义传输方式 1—带图片 2---不带图片',
  `WatchTime` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '抓拍时间，精确到毫秒',
  `WatchTime1` datetime DEFAULT NULL COMMENT '第一张图片的监测时间，精确到毫秒',
  `WatchTime2` datetime DEFAULT NULL COMMENT '第二张图片的监测时间，精确到毫秒',
  `WatchTime3` datetime DEFAULT NULL COMMENT '第三张图片的监测时间，精确到毫秒',
  `WatchTime4` datetime DEFAULT NULL COMMENT '第四张图片的监测时间，精确到毫秒',
  `DeviceDesc` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '设备监测地点描述，交管局统一下发',
  `CheckValue` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '文件加密的校验位，保留，暂时下端厂商填写值为固定值为-1',
  `StartTime` datetime DEFAULT NULL,
  `EndTime` datetime DEFAULT NULL,
  `PicNum` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT '照片数量，填写抓拍的照片数目',
  `FeaturePic` varchar(255) CHARACTER SET gbk DEFAULT NULL,
  `FileName` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT 'XML文件名称',
  `FilePath` varchar(255) CHARACTER SET gbk DEFAULT NULL COMMENT 'XML文件路径',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
